var dir_39ee8b67a15e0532c468a86d1fea7707 =
[
    [ "impl", "dir_ee45ea767a960ccb0ac3a6468bae3d54.html", "dir_ee45ea767a960ccb0ac3a6468bae3d54" ],
    [ "interp", "dir_b3a1a61df5da5a1e7b23865c86b29098.html", "dir_b3a1a61df5da5a1e7b23865c86b29098" ],
    [ "proto", "dir_076179cfa64f5d95b0a1aa32ebc1bf7f.html", "dir_076179cfa64f5d95b0a1aa32ebc1bf7f" ],
    [ "identity.h", "identity_8h.html", "identity_8h" ],
    [ "identity_test.cpp", "identity__test_8cpp.html", "identity__test_8cpp" ],
    [ "isometry2.h", "isometry2_8h.html", "isometry2_8h" ],
    [ "isometry2_test.cpp", "isometry2__test_8cpp.html", "isometry2__test_8cpp" ],
    [ "isometry3.h", "isometry3_8h.html", "isometry3_8h" ],
    [ "isometry3_test.cpp", "isometry3__test_8cpp.html", "isometry3__test_8cpp" ],
    [ "lie_group.h", "lie_2lie__group_8h.html", [
      [ "Group", "classsophus_1_1lie_1_1_group.html", "classsophus_1_1lie_1_1_group" ]
    ] ],
    [ "lie_group_test.cpp", "lie_2lie__group__test_8cpp.html", "lie_2lie__group__test_8cpp" ],
    [ "rotation2.h", "rotation2_8h.html", "rotation2_8h" ],
    [ "rotation2_test.cpp", "rotation2__test_8cpp.html", "rotation2__test_8cpp" ],
    [ "rotation3.h", "rotation3_8h.html", "rotation3_8h" ],
    [ "rotation3_test.cpp", "rotation3__test_8cpp.html", "rotation3__test_8cpp" ],
    [ "scaling.h", "scaling_8h.html", "scaling_8h" ],
    [ "scaling_test.cpp", "scaling__test_8cpp.html", "scaling__test_8cpp" ],
    [ "scaling_translation.h", "scaling__translation_8h.html", "scaling__translation_8h" ],
    [ "scaling_translation_test.cpp", "scaling__translation__test_8cpp.html", "scaling__translation__test_8cpp" ],
    [ "se3.h", "se3_8h.html", "se3_8h" ],
    [ "similarity2.h", "similarity2_8h.html", "similarity2_8h" ],
    [ "similarity2_test.cpp", "similarity2__test_8cpp.html", "similarity2__test_8cpp" ],
    [ "similarity3.h", "similarity3_8h.html", "similarity3_8h" ],
    [ "similarity3_test.cpp", "similarity3__test_8cpp.html", "similarity3__test_8cpp" ],
    [ "so3.h", "so3_8h.html", "so3_8h" ],
    [ "spiral_similarity2.h", "spiral__similarity2_8h.html", "spiral__similarity2_8h" ],
    [ "spiral_similarity2_test.cpp", "spiral__similarity2__test_8cpp.html", "spiral__similarity2__test_8cpp" ],
    [ "spiral_similarity3.h", "spiral__similarity3_8h.html", "spiral__similarity3_8h" ],
    [ "spiral_similarity3_test.cpp", "spiral__similarity3__test_8cpp.html", "spiral__similarity3__test_8cpp" ],
    [ "translation.h", "translation_8h.html", "translation_8h" ],
    [ "translation_test.cpp", "translation__test_8cpp.html", "translation__test_8cpp" ]
];